# The URL the site will be built for
title = "Yawuteva's Hella Groovy Website"
# base_url = "https://yawuteva.com"
base_url = "yawuteva.com"
description = "Yawuteva's official website"

compile_sass = true

theme = "andromeda0"

[extra]
header_links = [
    # {name = "Zola", url = "https://www.getzola.org/"},
    {name = "Home", url = "/yawuteva-site/"},
    {name = "Blog", url = "/yawuteva-site/blog"},
]
# license = "CC BY-NC 2.0"
# email = "info@yawuteva.com"
# name = "Jane Doe"
# favicon = "/images/favicon.ico"